client/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^account/$', views.account, name='account'),
    url(r'^watchlist/$', views.watchlist, name='watchlist'),
    url(r'^orders/$', views.orders, name='orders'),
    url(r'^trade/$', views.portfolio, name='portfolio'),
    url(r'^trade/(?P<order_id>[0-9]+)/$', views.edit_order, name='edit_order'),
    # url(r'^test/$', views.test, name='test'),
    url(r'^(?P<symbol>\w+)/$', views.stock, name='stock'),
    url(r'^(?P<symbol>\w+)/buy/$', views.buy, name='buy'),
    url(r'^(?P<symbol>\w+)/sell/$', views.sell, name='sell'),
]

hq/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^orders/$', views.orders, name='order_list'),
    url(r'^orders/all$', views.all, name='order_all'),
    url(r'^orders/tracker$', views.orderstracker, name='orders_tracker'),
    url(r'^orders/filter/(?P<order_filter>\w+)/$', views.filter, name='order_type'),
    url(r'^orders/status/(?P<order_status>\w+)/$', views.status, name='order_status'),
    url(r'^orders/(?P<order_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^orders/today/$', views.today, name='today'),
    url(r'^clients/$', views.clients, name='clients'),
    url(r'^clients/client/(?P<client_id>[0-9]+)/$', views.client, name='client'),
    url(r'^clients/create$', views.create_client, name='create_client'),
    url(r'^add/(?P<client_id>[0-9]+)/(?P<symbol>\w+)$', views.add_portfolio, name='add_portfolio'),
    url(r'^ordersapi/$', views.orders_api, name='orders_api'),
    url(r'^analytics/$', views.analytics, name='analytics'),
    url(r'^analyticscsv/$', views.analyticscsv, name='analyticscsv'),
    url(r'^endofday/$', views.endofday, name='endofday'),
    url(r'^split/(?P<order_id>[0-9]+)/$', views.order_split, name='order_split'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^dismissnotifications/$', views.dismiss_notifications, name='dismiss_notifications'),
    url(r'^change_market_status/$', views.change_market_status, name='change_market_status'),
]

roi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from roi import views as mainviews

urlpatterns = [
    url(r'^$', mainviews.index, name='main_url'),
    url(r'^api/last_order/', mainviews.last_order),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$','django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^market/', include('client.urls', namespace='client')),
    url(r'^hq/', include('hq.urls', namespace='hq')),
    url(r'^udffeed/', include('udffeed.urls', namespace='udffeed')),
    url(r'^password_reset/$','django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm'),
]

client/models.py
from django.db import models
from django.contrib.auth.models import User
from pseparser.models import Company
from django.shortcuts import get_object_or_404

# Create your models here.
class Client(models.Model):
    user = models.OneToOneField(User)
    last_name = models.CharField(max_length=20)
    first_name = models.CharField(max_length=20)
    wallet = models.DecimalField(decimal_places=2, max_digits=20)
    watchlist = models.ManyToManyField(Company, related_name='watching', blank=True)
    agents = models.CharField(max_length=20, blank=True)
    LANGUAGE_CHOICES = (
        ('ja', 'Japanese'),
        ('en', 'English'),
    )
    language = models.CharField(
        max_length=2,
        choices=LANGUAGE_CHOICES,
        default='en',
        blank=True
    )
    def __str__(self):
        return str(self.last_name +', '+ self.first_name)

class Order(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    client = models.ForeignKey(Client)
    stock = models.ForeignKey(Company)
    METHOD_CHOICES = (
        ('B', 'Buy'),
        ('S', 'Sell'),
    )
    method = models.CharField(
        max_length=1,
        choices=METHOD_CHOICES,
        default='B',
    )
    ORDER_TYPE_CHOICES = (
        ('L', 'Limit Order'),
        ('O', 'Stop Order'),
        ('C', 'One Cancel Other Order')
    )
    order_type = models.CharField(
        max_length=1,
        choices=ORDER_TYPE_CHOICES,
        default='L',
    )
    EXECUTION_TYPE_CHOICES = (
        ('OP', 'Order Price'),
        ('MO', 'Market Order'),
        ('BP', 'Best Price'),
        ('LO', 'Limit Order'),
        ('WO', 'Width Order'),
        ('OC', 'One Cancel Other Order')
    )
    execution_type = models.CharField(
        max_length=2,
        choices=EXECUTION_TYPE_CHOICES,
        default='OP',
    )
    price = models.DecimalField(decimal_places=2, max_digits=20)
    upper_limit = models.DecimalField(decimal_places=2, max_digits=20)
    units = models.IntegerField()
    EXPIRATION_CHOICES = (
        ('C', 'Good Til Cancelled'),
        ('D', 'Good Til Date'),
    )
    expiration = models.CharField(
        max_length=1,
        choices=EXPIRATION_CHOICES,
        default='C',
    )
    STATUS_CHOICES = (
        ('Pen', 'Pending'),
        ('Par', 'Queued'),
        ('Inc', 'Partial'),
        ('Exe', 'Executed'),
        ('Rev', 'Processing'),
        ('Rej', 'Rejected'),
        ('Can', 'Cancelled'),
    )
    status = models.CharField(
        max_length=3,
        choices=STATUS_CHOICES,
        default='Pen',
    )
    charge = models.DecimalField(decimal_places=2, max_digits=20, default=0)
    others = models.CharField(max_length=30, blank=True, null=True)


class Transaction(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(decimal_places=2, max_digits=20, default=0)
    client = models.ForeignKey(Client)
    TRANSACTION_TYPE_CHOICES = (
        ('B', 'Buy'),
        ('S', 'Sell'),
        ('D', 'Dividend'),
        ('W', 'Withdrawal'),
        ('A', 'Add Fund'),
    )
    order_type = models.CharField(
        max_length=1,
        choices=TRANSACTION_TYPE_CHOICES,
        default='B',
    )
    note = models.CharField(max_length=30, blank=True, null=True)


class AdminNotification(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    client = models.ForeignKey(Client)
    order = models.IntegerField()
    message = models.CharField(max_length=30, blank=True, null=True)
    seen = models.IntegerField(default=0)

    def __str__(self):
        return str(self.message)

class Alert(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=30, blank=True, null=True)
    client = models.ForeignKey(Client)
    seen = models.IntegerField(default=0)

    def __str__(self):
        return str(self.message)

hq/models.py
from django.db import models

# Create your models here.

client/views.py
from django.core.mail import EmailMessage
from django.shortcuts import render, get_object_or_404
from django.template import Context
from django.template.loader import get_template

import requests as requests
import logging


from pseparser.models import *
from roi import settings
from .models import *
from datetime import datetime, date, timedelta
from .forms import *
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from django.db.models import Sum, Case, When, F, FloatField


LOGGER = logging.getLogger(__name__)



def fetch_stocks():
    STOCK_PRICES = "http://phisix-api2.appspot.com/stocks.json"

    STOCK_PRICES2 = "http://api.pse.tools/api/stocks"
    

    try:
        response = requests.get(STOCK_PRICES2)
        json_response = response.json()
        list_length = len(json_response)

        indices = Index.objects.all()
        stocks = json_response['data']

        datetime = json_response['timestamp'].split(" ")


        # response = requests.get(STOCK_PRICES)
        # json_response = response.json()
        # list_length = len(json_response)

        # indices = Index.objects.all()

        # stocks = json_response['stock']
        # datetime = json_response['as_of'].split("T")
        date = datetime[0]

        # for stock in stocks:
        #     symbol = stock['symbol']
        #     volume = stock['volume']
        #     percent_change = stock['percent_change'] 

        #     if percent_change > 0:
        #         indicator="U"
        #     elif percent_change < 0:
        #         indicator="D"
        #     else:
        #         indicator="N"

        #     for index in indices:
        #         if index.security_symbol == symbol:
        #             index.total_volume = volume
        #             index.percentage_change_close = percent_change
        #             index.indicator = indicator

        #             index.save()
        #             LOGGER.info("updating index")



        for stock in stocks:
            symbol = stock['symbol']
            
            open_price = stock['open']
            high_price = stock['high']
            low_price = stock['low']

            last_price = stock['last']
            changec = stock['change']
            
            if changec is not None:
                percent_change = float(stock['change'])

            volume = stock['volume']
            company = Company.objects.filter(symbol=symbol).first()

            if company is not None:

                stockpricetoday = StockPrice.objects.filter(company=company, date_details=date).first()

                if percent_change > 0:
                    indicator="U"
                elif percent_change < 0:
                    indicator="D"
                else:
                    indicator="N"

                if stockpricetoday is None:

                    StockPrice.objects.create(
                        company=company,
                        date_details=date,
                        open_price = open_price,
                        low_price = low_price,
                        high_price = high_price,
                        indicator = indicator,
                        percentage_change_close = percent_change,
                        total_volume = volume,
                        last_traded_price = last_price
                    )

                    print ("adding new date for")

                else:
                    stockpricetoday.total_volume = volume
                    stockpricetoday.indicator = indicator
                    stockpricetoday.last_traded_price = last_price
                    stockpricetoday.percentage_change_close = percent_change

                    stockpricetoday.low_price = low_price
                    stockpricetoday.high_price = high_price
                    

                    # LOGGER.info("updating price")

                    print ("updating")


                    stockpricetoday.save()

    except:  # This is the correct syntax        print ("error")
        print ("error")

# Create your views here.
@login_required(login_url='login')
def index(request):

    fetch_stocks()

    


    marketstatus = SystemOption.objects.filter(name='marketstatus').first()

    client = request.user.client

    alerts = client.alert_set.filter(seen=0)

    for alert in alerts:
        alert.seen = 1
        alert.save()

    bought = client.order_set.values('stock__symbol').filter(method='B').exclude(
        status__in=['Pen', 'Par', 'Rev', 'Rej', 'Can']).annotate(price=Sum('price')).annotate(units=Sum('units')).annotate(charge=Sum('charge'))
    sold = client.order_set.values('stock__symbol').filter(method='S').exclude(
        status__in=['Pen', 'Par', 'Rev', 'Rej', 'Can']).annotate(price=Sum('price')).annotate(units=Sum('units')).annotate(charge=Sum('charge'))

    sold_stocks = {}

    for item in sold:
        company = Company.objects.get(symbol=item['stock__symbol'])
        sold_stocks[company] = item

    portfolio = {}
    total_stock_value = 0

    for item in bought:
        company = Company.objects.get(symbol=item['stock__symbol'])
        if company in sold_stocks:
            item['units'] = item['units'] - sold_stocks[company]['units']
            item['price'] = item['price'] - sold_stocks[company]['price']
            available_stocks = client.order_set.filter(method='B',stock=company).exclude(
                status__in=['Pen', 'Par', 'Rev', 'Rej', 'Can']).order_by('id')
            number_of_stocks_sold = sold_stocks[company]['units']

            #filter remaining stock
            last_stock_price = 0
            last_stock_units = 0
            units_remaining = 0

            for this_stock in available_stocks:
                if number_of_stocks_sold >= this_stock.units:
                    available_stocks = available_stocks.exclude(id=this_stock.id)
                number_of_stocks_sold = number_of_stocks_sold - this_stock.units
                if(number_of_stocks_sold <= 0):
                    last_stock_price = this_stock.price
                    last_stock_units = this_stock.units
                    units_remaining = number_of_stocks_sold*-1
                    available_stocks = available_stocks.exclude(id=this_stock.id)
                    break

            last_price_per_unit = (last_stock_price/last_stock_units)
            sum_price = available_stocks.aggregate(sum_price=Sum('price'))['sum_price']

            if sum_price:
                sum_price = float(sum_price) + float(last_price_per_unit*units_remaining)
            else:
                sum_price = float(last_price_per_unit*units_remaining)

            item['price'] = sum_price



        if item['units'] > 0:

            item['stockprice'] = company.stockprice_set.order_by('-date_details').first()
            
            latest_stock_item = company.stockprice_set.last()
            total_stock_value = total_stock_value + (item['units'] * latest_stock_item.last_traded_price)
            portfolio[company] = item


            lastclose=float(latest_stock_item.last_traded_price)/((float(latest_stock_item.percentage_change_close)/100)+1)
            item['change']=float(latest_stock_item.last_traded_price)-lastclose


    pending_stocks = client.order_set.filter(status__in=['Pen', 'Rev'], method='B').aggregate(price=Sum('price'))[
        'price']
    if not pending_stocks:
        pending_stocks = 0

    order_set = client.order_set.order_by('-id')

    wallet_set = client.transaction_set.order_by('-id')

    

    companies_array = []

    companiesfeed = Company.objects.order_by('symbol')
    for company_feed in companiesfeed:
        stockprice = StockPrice.objects.filter(company=company_feed).last()
        if stockprice is not None:
            companies_array.append({'stock':company_feed, 'value':(stockprice.total_volume*stockprice.last_traded_price), 'volume':stockprice.total_volume, 'change':stockprice.percentage_change_close, 'lastprice':stockprice.last_traded_price})


    losers = sorted(companies_array, key=lambda k: k['change'])[:10]
    winners = sorted(companies_array, key=lambda k: k['change'], reverse=True)[:10]
    active = sorted(companies_array, key=lambda k: k['value'], reverse=True)[:10]


    today_transactions = client.order_set.values('stock__symbol').filter(method='B', status__in=['Exe'],
                                                    last_updated__date=date.today()).annotate(price=Sum('price')).annotate(units=Sum('units')).annotate(charge=Sum('charge'))

    today_stocks = {}

    recent_change = 0

    for item in today_transactions:
        company = Company.objects.get(symbol=item['stock__symbol'])
        today_stocks[company] = item
        



    for item in portfolio:
        company = Company.objects.get(symbol=item.symbol)
        
        if company in today_stocks:

            stock_item = company.stockprice_set.last()

            today_ex_portfolio_units = portfolio[company]['units'] - today_stocks[company]['units']
            today_ex_portfolio_price = portfolio[company]['price'] - today_stocks[company]['price']

            if today_ex_portfolio_units > 0:
                stock_change = today_ex_portfolio_price * stock_item.percentage_change_close/100
                recent_change = recent_change + stock_change
            else:
                today_only_portfolio_price = today_stocks[company]['price']

                stock_change = (stock_item.last_traded_price*today_stocks[company]['units']) - today_only_portfolio_price
                recent_change = recent_change + stock_change
        else:
            stock_item = company.stockprice_set.last()

            stock_change = portfolio[company]['units'] * (stock_item.last_traded_price - (stock_item.last_traded_price/((stock_item.percentage_change_close/100)+1)))

hq/templates/hq/client_detail.html
{% extends 'base-hq.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}

{% block body %}
<br><br>
<table id="admin">
    <tr><th>Client:</th><td>{{ client.user }}</td></tr>
    <tr><th>Last Name:</th><td>{{ client.last_name }}</td></tr>
    <tr><th>First Name:</th><td>{{ client.first_name }}</td></tr>
    <tr><th>Current Walle:</th><td>{{ client.wallet }}</td></tr>
   
</table>

<form action="{% url 'hq:client' client.id %}" method="post"  id="wallet-form">

{{ form.non_field_errors }}
{% csrf_token %}

<div class="fieldWrapper">
    {{ form.units.errors }}
    <input id="id_wallet" name="wallet" value="0">
</div>

<a href="#" onclick="formvalidate();" class="btn btn-primary">Add Fund/Withdraw</a>



<script>

        function formvalidate() {

          Amount = $("#id_wallet").val();
          console.log('add');

          var r = confirm("Add/Withdraw Fund from Wallet\nAmount:" +  Amount);
          if (r == true) {
              $( "#wallet-form" ).submit();
          } else {
          }
        }

</script>




</form>

<table id="table_portfolio" class="table" cellpadding="10">
        <thead>
          <tr>
          	<th class="stock-symbol">Symbol</th>
            <th class="stock-name-table">Stock Name</th>
            <th class="stock-holding-table">Holding</th>
            <th class="stock-sell-table">Average Price</th>
            <th class="stock-cost-table">Cost</th>
          </tr>
        </thead>
        <tbody>
          {% for key, value in portfolio.items %}
          <tr>
          	<td>{{ key.symbol }}</td>
            <td class="stock-name-table"><a href="{% url 'client:stock' key.symbol %}">{{ key }}</a></td>
            <td class="stock-holding-table">{{ value.units }}</td>
            <td class="stock-sell-table">
              {% if value.price|div:value.units >= 1 %}
              {{ value.price|div:value.units|floatformat:2 }}
              {% else %}
              {{ value.price|div:value.units|floatformat:4 }}
              {% endif %}
            </td>
            <td class="stock-cost-table portfolio-cost-table">{{ value.price|intcomma }}</td>

          </tr>
          {% endfor %}
        </tbody>
      </table>




{% endblock %}

hq/templates/hq/clients.html
{% extends 'base-hq.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<script src="http://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('#ordersTable').DataTable({
        "order": [[ 0, "desc" ]],
        "pageLength": 20
    });
    console.log('lalala');
});
</script>
{% endblock %}

{% block body %}

<a href="{% url 'hq:create_client' %}" class="btn btn-primary btn-sm">CREATE NEW CLIENT</a>
<table id="ordersTable">
    <thead>
        <tr>
            <th>User ID</th>
            <th>Username</th>
            <th>Last Name</th>
            <th>First Name</th>
            <th>E-Mail</th>
            <th>Agent</th>
            <th>Wallet</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for client in clients %}
        <tr>
            <td>{{client.id }}</td>
            <td>{{client.user }}</td>
            <td>{{client.last_name }}</td>
            <td>{{client.first_name }}</td>
            <td>{{client.email }}</td>
            <td>{{client.agents }}</td>
            <td>{{client.wallet }}</a></td>
            <td><a href="{% url 'hq:client' client.id %}" target="_blank" class="btn btn-primary btn-lg">View Client</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

hq/templates/hq/order_detail.html
{% extends 'base-hq.html' %}
{% load static %}

{% block body %}
<a href="{% url 'hq:order_list' %}" class="btn btn-info"><< Back to orders list</a>
<br><br>
<table id="admin">
    <tr><th>Timestamp:</th><td>{{ order.date_created }}</td></tr>
    <tr><th>Client:</th><td>{{ order.client }}</td></tr>
    <tr><th>Username:</th><td>{{ order.client.user }}</td></tr>
    <tr><th>Stock:</th><td>{{ order.stock }}</td></tr>
    <tr><th>Method:</th><td id="method">{{ order.get_method_display }}</td></tr>
    <tr><th>Type:</th><td id="ordertype">{{ order.get_order_type_display }}</td></tr>
    <tr><th>Execution:</th><td id="execution-type">{{ order.get_execution_type_display }}</td></tr>
    <tr><th>Aux Value:</th><td>{{ order.upper_limit }}</td></tr>
    <tr><th>Expiration:</th><td>{{ order.get_expiration_display }}</td></tr>
    <tr><th>Current Status:</th><td>{{ order.get_status_display }}</td></tr>
    {% if order.status == 'Exe'  or order.status == 'Can' %}
    <tr><th>Price:</th><td>{{ order.price }}</td></tr>
    <tr><th>Units:</th><td>{{ order.units }}</td></tr>
    <tr><th>Override:</th><td><a href="http://tradepro-mft.com/admin/client/order/{{order.id}}/change/">Override</button></a></td>
    {% endif %}
</table>
{% if order.status == 'Pen' or order.status == 'Rev' or order.status == 'Par' %}
<form action="{% url 'hq:detail' order.id %}" method="post">
{% csrf_token %}
{{ form.non_field_errors }}
<div class="fieldWrapper">
    <label for="{{ form.units.id_for_label }}">Price:</label>
    <input id="stockprice" step="0.0001" type="number" value="0">
</div>
<div class="fieldWrapper">
    {{ form.units.errors }}
    <label for="{{ form.units.id_for_label }}">Units:</label>
    {{ form.units }}
</div>
<div class="fieldWrapper">
    {{ form.price.errors }}
    <label for="{{ form.price.id_for_label }}">Cost:</label>
    {{ form.price }}
</div>
<div class="fieldWrapper">
    <label for="{{ form.charge.id_for_label }}">Charge:</label>
    {{ form.charge }}
</div>
<div class="fieldWrapper">
    <label for="{{ form.charge.id_for_label }}">Exec by:</label>
    <input type="text" id="id_others" name="others" value="{{ admin }}">
</div>

    

<!--<button id="id_status" name="status" class="button expanded" value="Pen" type="submit">Mark as Pending</button>-->

<button id="id_status" name="status" class="button expanded" value="Pen" type="submit">Mark as Pending</button>
<button id="id_status" name="status" class="button expanded" value="Par" type="submit">Mark as Queued</button>
<button id="id_status" name="status" class="button expanded" value="Rev" type="submit">Mark as Processing</button>
<button id="id_status" name="status" class="button expanded" value="Exe" type="submit">Mark as Executed</button>
<button id="id_status" name="status" class="button expanded" value="Can" type="submit">Mark as Cancelled</button>




<!--<select id="id_status" name="status">
<option value="Pen">Pending</option>
<option value="Par">Partially executed</option>
<option value="Exe" selected="selected">Executed</option>
<option value="Rev">Revised</option>
<option value="Rej">Rejected</option>
<option value="Can">Cancelled</option>
</select>-->
</form>

<a href="{% url 'hq:order_split' order.id %}">SPLIT ORDER</a>

<script>




$( function() {

    method = '{{ order.get_method_display }}';

    if(method == 'Sell') {
        console.log(method = 'sell');
        charge = parseFloat($('#id_charge').val());
        $('#id_charge').val(charge*(1));

    } else {
        console.log('buy');
    }


    totalcost = $("#id_price").val();
    units = $("#id_units").val();

    $("#stockprice").val(parseInt(totalcost)/parseInt(units));


});

$("#stockprice").keyup(function() {
    stockgoes = $("#stockprice").val();
    units = $("#id_units").val();
    lastprice2 = parseFloat(stockgoes);
    lastprice3 = (lastprice2*units);
    commision = lastprice3*0.01;


    if(method == 'Sell') {
        if (commision <= 150) {
              sellcommision = lastprice3 * 0.005;
              lastpricewithcommision = lastprice3 - (168 + lastprice3*0.00015 + sellcommision);
          } else {
              lastpricewithcommision = lastprice3*0.98365;
          }
    } else {
        if (commision <= 150) {
            lastpricewithcommision = lastprice3 + 168 + lastprice3*0.00015;
        } else {
            lastpricewithcommision = lastprice3*1.01135;
        }
    }




    $("#id_price").val(lastprice3.toFixed(2));

});

$("#id_units").keyup(function() {
    stockgoes = $("#stockprice").val();
    units = $("#id_units").val();
    lastprice2 = parseFloat(stockgoes);
    lastprice3 = (lastprice2*units);
    commision = lastprice3*0.01;



    if(method == 'sell') {
        if (commision <= 150) {
              sellcommision = lastprice3 * 0.005;
              lastpricewithcommision = lastprice3 - (168 + lastprice3*0.00015 + sellcommision);
          } else {
              lastpricewithcommision = lastprice3*0.98365;
          }
    } else {
        if (commision <= 150) {
            lastpricewithcommision = lastprice3 + 168 + lastprice3*0.00015;
        } else {
            lastpricewithcommision = lastprice3*1.01135;
        }
    }

    finalcomision = lastpricewithcommision-lastprice3;

    $("#id_charge").val(finalcomision.toFixed(2));




    $("#id_price").val(lastprice3.toFixed(2));

});



</script>


{% endif %}
{% endblock %}

hq/templates/hq/orders.html
{% extends 'base-hq.html' %}
{% load static %}
{% load mathfilters %}

{% block head %}
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<script src="http://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('#ordersTable').DataTable({
        "order": [[ 0, "desc" ]],
        "pageLength": 20
    });
    console.log('lalala');
});
</script>
{% endblock %}

{% block body %}
<table id="ordersTable">
    <thead>
        <tr>
            <th>Requested</th>
            <th>User ID</th>
            <th>Client</th>
            <th>Method</th>
            <th>Type - Execution</th>
            <th>Stock Symbol</th>
            <th>Units</th>
            <th>Price</th>
            <th>Status</th>
            <th>Exp</th>
            <th>Exec by</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
        <tr class="{{ order.order_type }}">
            <td>{{order.id|stringformat:"04d" }} {{order.date_created|date:"r"}}</td>
            <td>{{ order.client.user }} ({{order.client.wallet}})</td>
            <td>{{order.client}}</td>
            <td>{{order.get_method_display}}</td>
            <td>
                {% if order.order_type = 'O' %}
                S | {{ order.execution_type }}
                {% else %}
                L | {{ order.execution_type }}
                {% endif %}
            </td>
            <td>{{order.stock.symbol}}</td>
            <td>{{order.units}}</td>
            <td>
                {% if order.method = 'B' %}
                    {% if order.execution_type = 'WO' %}
                    {{order.price|div:order.units}} - {{order.upper_limit}}
                    {% else %}
                    {{order.price|div:order.units}}
                    {% endif %}
                {% else %}
                    {% if order.execution_type = 'WO' %}
                    {{order.upper_limit}} - {{order.price|div:order.units}}
                    {% else %}
                    {{order.price|div:order.units}}
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {% if order.status = 'Pen' or order.status = 'Rev' or order.status = 'Par' or order.status = 'Inc' %}
                <a href="{% url 'hq:detail' order.id %}" class="btn btn-primary btn-sm">{{order.get_status_display}}</a>
                {% else %}
                <a href="{% url 'hq:detail' order.id %}" class="btn btn-secondary btn-sm">{{order.get_status_display}}</a>
                {% endif %}
            </td>
            <td>{{order.expiration}}</td>
            <td>{{order.others}} | {{order.last_updated|date:"r"}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}