hq/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^orders/$', views.orders, name='order_list'),
    url(r'^orders/all$', views.all, name='order_all'),
    url(r'^orders/tracker$', views.orderstracker, name='orders_tracker'),
    url(r'^orders/filter/(?P<order_filter>\w+)/$', views.filter, name='order_type'),
    url(r'^orders/status/(?P<order_status>\w+)/$', views.status, name='order_status'),
    url(r'^orders/(?P<order_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^orders/today/$', views.today, name='today'),
    url(r'^clients/$', views.clients, name='clients'),
    url(r'^clients/client/(?P<client_id>[0-9]+)/$', views.client, name='client'),
    url(r'^clients/create$', views.create_client, name='create_client'),
    url(r'^add/(?P<client_id>[0-9]+)/(?P<symbol>\w+)$', views.add_portfolio, name='add_portfolio'),
    url(r'^ordersapi/$', views.orders_api, name='orders_api'),
    url(r'^analytics/$', views.analytics, name='analytics'),
    url(r'^analyticscsv/$', views.analyticscsv, name='analyticscsv'),
    url(r'^endofday/$', views.endofday, name='endofday'),
    url(r'^split/(?P<order_id>[0-9]+)/$', views.order_split, name='order_split'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^dismissnotifications/$', views.dismiss_notifications, name='dismiss_notifications'),
    url(r'^change_market_status/$', views.change_market_status, name='change_market_status'),
]

roi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from roi import views as mainviews

urlpatterns = [
    url(r'^$', mainviews.index, name='main_url'),
    url(r'^api/last_order/', mainviews.last_order),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$','django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^market/', include('client.urls', namespace='client')),
    url(r'^hq/', include('hq.urls', namespace='hq')),
    url(r'^udffeed/', include('udffeed.urls', namespace='udffeed')),
    url(r'^password_reset/$','django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm'),
]

hq/models.py
from django.db import models

# Create your models here.

hq/forms.py
from django import forms
from client.models import *
from pseparser.models import *
from django.contrib.auth.models import User

class AdminOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['price', 'units', 'status', 'charge', 'others']

class AddWallet(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['wallet']

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

class ClientCreateForm(forms.ModelForm):
    class Meta:
        model = Client
        exclude = ['user']

class AddPortfolio(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['method', 'order_type', 'execution_type', 'price', 'upper_limit', 'units', 'expiration', 'status', 'charge', 'others']

class OrderSplit(forms.Form):
    split1 = forms.IntegerField(label="Split1", required=False)
    split2 = forms.IntegerField(label="Split2", required=False)

hq/views.py
from django.shortcuts import render
from client.models import *
from .forms import *
from django.core.urlresolvers import reverse
from django.core.mail import EmailMessage
from django.template import Context
from django.template.loader import get_template
from django.views.decorators.csrf import csrf_exempt

from django.http import HttpResponse, JsonResponse, HttpResponseRedirect



# from datetime import datetime, date, timedelta
import datetime
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from pseparser.models import Company
from django.shortcuts import get_object_or_404

from roi import settings

import requests as requests

import json

import csv

from django.db.models import Sum, Case, When, F, FloatField



# Create your views here.
@login_required(login_url='login')
def all(request):
    orders = Order.objects.all().order_by('id')
    return render(request, 'hq/orders.html', {'orders': orders})


# Create your views here.
@login_required(login_url='login')
def alldate(request):
    orders = Order.objects.all().order_by('id')
    return render(request, 'hq/orders.html', {'orders': orders})


@login_required(login_url='login')
def orders(request):
    orders = Order.objects.all().order_by('id').exclude(status__in=['Exe', 'Can'])
    return render(request, 'hq/orders.html', {'orders': orders})

@login_required(login_url='login')
def orderstracker(request):
    orders = Order.objects.all().order_by('id').exclude(status__in=['Exe', 'Can'])


    for order in orders:
        current = order.stock.stockprice_set.order_by('-date_details').first()
        orderprice = order.price/order.units

        order.lastprice = current.last_traded_price

        order.percent = ((orderprice/current.last_traded_price) - 1)*100

        order.red = 1-(abs(order.percent)/5)
        order.yellow = abs(order.percent)*25


    return render(request, 'hq/orders_tracker.html', {'orders': orders})

@login_required(login_url='login')
def clients(request):
    clients = Client.objects.all().order_by('id')

    return render(request, 'hq/clients.html', {'clients': clients})

@login_required(login_url='login')
def filter(request, order_filter):
    orders = Order.objects.filter(execution_type=order_filter)
    return render(request, 'hq/orders_filter.html', {'orders': orders})

@login_required(login_url='login')
def today(request):
    orders = Order.objects.filter(status__in=['Exe'], last_updated__date=datetime.date.today())
    return render(request, 'hq/orders_today.html', {'orders': orders})


@login_required(login_url='login')
def status(request, order_status):
    orders = Order.objects.filter(status=order_status)
    return render(request, 'hq/orders_filter.html', {'orders': orders})

@login_required(login_url='login')
def detail(request, order_id):
    admin = request.user
    order = Order.objects.get(id=order_id)
    old_price = order.price
    old_charge =  order.charge

    if request.method == 'POST':
        form = AdminOrderForm(request.POST, instance=order)
        print(form)
        if form.is_valid():
            print('old price', old_price)
            print('new price', form.cleaned_data['price'])
            price_difference = old_price - form.cleaned_data['price']
            charge_difference = old_charge - form.cleaned_data['charge']
            client = order.client
            if order.status == 'Exe':
                if order.method == 'B':
                    client.wallet = client.wallet + price_difference + charge_difference
                else:
                    client.wallet = client.wallet + (form.cleaned_data['price'] + form.cleaned_data['charge'])

            if order.status == 'Can':
                if order.method == 'B':
                    client.wallet = client.wallet + old_price + form.cleaned_data['charge']
                    
                    template = get_template('cancel-template.txt')
                    context = Context({
                        'content': "content",
                    })
                    email_body = template.render(context)
                    EmailMessage(
                        subject='Order Cancelled',
                        body= email_body,
                        from_email=settings.EMAIL_HOST_USER,
                        to=settings.EDIT_RECIPIENTS
                    ).send()
                else:
                    client.wallet = client.wallet + form.cleaned_data['charge']
                    
                    template = get_template('cancel-template.txt')
                    context = Context({
                        'content': 'content',
                    })
                    email_body = template.render(context)
                    EmailMessage(
                        subject='Order Cancelled',
                        body= email_body,
                        from_email=settings.EMAIL_HOST_USER,
                        to=settings.EDIT_RECIPIENTS
                    ).send()

            client.wallet = client.wallet 

            client.save()
            form.save()
            #return HttpResponseRedirect(reverse('hq:detail'))
            return HttpResponseRedirect(reverse('hq:detail', args=(order_id,)))

    else:
        form = AdminOrderForm(instance=order)

    return render(request, 'hq/order_detail.html', {'form':form, 'order': order, 'admin': admin})

@login_required(login_url='login')
def order_split(request, order_id):
    admin = request.user
    order = Order.objects.get(id=order_id)
    units = order.units
    price = order.price

    if request.method == 'POST':
        form = OrderSplit(request.POST)
        if form.is_valid():
            first_split = form.cleaned_data['split1']
            second_split = form.cleaned_data['split2']

            priceperunit = price/units

            if units == first_split+second_split:

                Order.objects.create(
                    client = order.client,
                    stock = order.stock,
                    method = order.method,
                    order_type = order.order_type,
                    execution_type = order.execution_type,
                    price = priceperunit*first_split,
                    upper_limit = order.upper_limit,
                    units = first_split,
                    expiration = order.expiration,
                    status = order.status,
                    charge = order.charge,
                    others = order.others
                )

                Order.objects.create(
                    client = order.client,
                    stock = order.stock,
                    method = order.method,
                    order_type = order.order_type,
                    execution_type = order.execution_type,
                    price = priceperunit*second_split,
                    upper_limit = order.upper_limit,
                    units = second_split,
                    expiration = order.expiration,
                    status = order.status,
                    charge = order.charge,
                    others = order.others
                )

                order.status = 'Can'
                order.save()

            return HttpResponseRedirect(reverse('hq:order_list'))
    else:
        form = OrderSplit()

    return render(request, 'hq/order_split.html', {'form':form, 'order': order, 'admin': admin})

 # if request.method == 'POST':
 #        order_form = AddPortfolio(request.POST)
 #        if order_form.is_valid():
 #            order = Order(client=client, stock=company)
 #            order_form = AddPortfolio(request.POST, instance=order)
 #            order_form.save()


 #            return HttpResponseRedirect(reverse('hq:add_portfolio', args=(client_id,symbol,)))

 #    else:
 #        order_form = AddPortfolio()



 #            return HttpResponseRedirect(reverse('hq:detail', args=(order_id,)))


 #    return render()


@login_required(login_url='login')
def client(request, client_id):
    admin = request.user

    client = Client.objects.get(id=client_id)

    cid = client_id

    bought = client.order_set.values('stock__symbol').filter(method='B').exclude(
        status__in=['Pen', 'Par', 'Rev', 'Rej', 'Can']).annotate(price=Sum('price')).annotate(units=Sum('units'))
    sold = client.order_set.values('stock__symbol').filter(method='S').exclude(
        status__in=['Pen', 'Par', 'Rev', 'Rej', 'Can']).annotate(price=Sum('price')).annotate(units=Sum('units'))

    sold_stocks = {}

    for item in sold:
        company = Company.objects.get(symbol=item['stock__symbol'])
        sold_stocks[company] = item

    portfolio = {}
    total_stock_value = 0

    for item in bought:
        company = Company.objects.get(symbol=item['stock__symbol'])
        if company in sold_stocks:
            item['units'] = item['units'] - sold_stocks[company]['units']
            item['price'] = item['price'] - sold_stocks[company]['price']
            available_stocks = client.order_set.filter(method='B',stock__company=company).exclude(
                status__in=['Pen', 'Par', 'Rev', 'Rej', 'Can']).order_by('id')
            number_of_stocks_sold = sold_stocks[company]['units']

            #filter remaining stock
            last_stock_price = 0
            last_stock_units = 0
            units_remaining = 0

            for this_stock in available_stocks:
                if number_of_stocks_sold >= this_stock.units:
                    available_stocks = available_stocks.exclude(id=this_stock.id)
                number_of_stocks_sold = number_of_stocks_sold - this_stock.units
                if(number_of_stocks_sold <= 0):
                    last_stock_price = this_stock.price
                    last_stock_units = this_stock.units
                    units_remaining = number_of_stocks_sold*-1

hq/templates/base-hq.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/united/bootstrap.min.css">
        <script type="text/javascript" src="https://raw.githubusercontent.com/flouthoc/blinkTitle.js/master/index.js"></script>

        {% block head %}
        {% endblock %}

    </head>
    <body>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Trade Pro Admin</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'hq:order_list' %}">Orders</a></li>
                <li><a href="{% url 'hq:clients' %}">Clients</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Order Filters <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'hq:order_list' %}/filter/OP/">Order Price</a></li>
                    <li><a href="{% url 'hq:order_list' %}/filter/MO/">Market Order</a></li>
                    <li><a href="{% url 'hq:order_list' %}/filter/LO/">Limit Order</a></li>
                    <li><a href="{% url 'hq:order_list' %}/filter/BP/">Best Price</a></li>
                    <li><a href="{% url 'hq:order_list' %}/filter/WO/">Width Order</a></li>
                    <li><a href="{% url 'hq:order_list' %}/status/Pen/">Pending</a></li>
                    <li><a href="{% url 'hq:order_list' %}/status/Par/">Queued</a></li>
                    <li><a href="{% url 'hq:order_list' %}/status/Rev/">Processing</a></li>
                    <li><a href="{% url 'hq:order_list' %}/status/Exe/">Executed</a></li>
                    <li><a href="{% url 'hq:order_list' %}/status/Can/">Cancelled</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Change Market Status<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="http://tradepro-mft.com/hq/change_market_status/?status=Pre-Open">Pre Open</a></li>
                    <li><a href="http://tradepro-mft.com/hq/change_market_status/?status=Market Open">Market Open</a></li>
                    <li><a href="http://tradepro-mft.com/hq/change_market_status/?status=Recess">Recess</a></li>
                    <li><a href="http://tradepro-mft.com/hq/change_market_status/?status=Pre Close">Pre Close</a></li>
                    <li><a href="http://tradepro-mft.com/hq/change_market_status/?status=Market Close">Market Close</a></li>
                  </ul>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="http://172.104.167.62/logout">Logout</a></li>
              </ul>
            </div>
          </div>
        </nav>


        

        <div class="container">

        <div id="alerts"></div>

        <script>

            $.getJSON( "http://tradepro-mft.com/hq/notifications/", function( data ) {

                fulldata = data;
                notificationarray = fulldata.array
              
                $.each( notificationarray, function( key, val ) {
                   $('#alerts').append("<div id=\"notifications\" class=\"alert alert-danger alert-dismissible\" role=\"alert\"><button type=\"button\" onclick=\"dismiss(" + val.id + ")\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>" + val.message + " | <a href=\"http://tradepro-mft.com/hq/orders/"+ val.order_id + "\" target=\"_blank\">VIEW ORDER</a></div>");
                });
            });

            

            setInterval(function() {

                $('#alerts').html("");

                $.getJSON( "http://tradepro-mft.com/hq/notifications/", function( data ) {

                    fulldata = data;
                    notificationarray = fulldata.array
                  
                    $.each( notificationarray, function( key, val ) {
                       $('#alerts').append("<div id=\"notifications\" class=\"alert alert-danger alert-dismissible\" role=\"alert\"><button type=\"button\" onclick=\"dismiss(" + val.id + ")\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>" + val.message + " | <a href=\"http://tradepro-mft.com/hq/orders/"+ val.order_id + "\" target=\"_blank\">VIEW ORDER</a></div>");
                    });
                });
            }, 10000);

            function dismiss(id) {
                $.post("http://tradepro-mft.com/hq/dismissnotifications/?id="+id);
            }

        </script>

        {% block body %}
        {% endblock %}
        </div>

     

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>