client/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^account/$', views.account, name='account'),
    url(r'^watchlist/$', views.watchlist, name='watchlist'),
    url(r'^orders/$', views.orders, name='orders'),
    url(r'^trade/$', views.portfolio, name='portfolio'),
    url(r'^trade/(?P<order_id>[0-9]+)/$', views.edit_order, name='edit_order'),
    # url(r'^test/$', views.test, name='test'),
    url(r'^(?P<symbol>\w+)/$', views.stock, name='stock'),
    url(r'^(?P<symbol>\w+)/buy/$', views.buy, name='buy'),
    url(r'^(?P<symbol>\w+)/sell/$', views.sell, name='sell'),
]

hq/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^orders/$', views.orders, name='order_list'),
    url(r'^orders/all$', views.all, name='order_all'),
    url(r'^orders/tracker$', views.orderstracker, name='orders_tracker'),
    url(r'^orders/filter/(?P<order_filter>\w+)/$', views.filter, name='order_type'),
    url(r'^orders/status/(?P<order_status>\w+)/$', views.status, name='order_status'),
    url(r'^orders/(?P<order_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^orders/today/$', views.today, name='today'),
    url(r'^clients/$', views.clients, name='clients'),
    url(r'^clients/client/(?P<client_id>[0-9]+)/$', views.client, name='client'),
    url(r'^clients/create$', views.create_client, name='create_client'),
    url(r'^add/(?P<client_id>[0-9]+)/(?P<symbol>\w+)$', views.add_portfolio, name='add_portfolio'),
    url(r'^ordersapi/$', views.orders_api, name='orders_api'),
    url(r'^analytics/$', views.analytics, name='analytics'),
    url(r'^analyticscsv/$', views.analyticscsv, name='analyticscsv'),
    url(r'^endofday/$', views.endofday, name='endofday'),
    url(r'^split/(?P<order_id>[0-9]+)/$', views.order_split, name='order_split'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^dismissnotifications/$', views.dismiss_notifications, name='dismiss_notifications'),
    url(r'^change_market_status/$', views.change_market_status, name='change_market_status'),
]

roi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from roi import views as mainviews

urlpatterns = [
    url(r'^$', mainviews.index, name='main_url'),
    url(r'^api/last_order/', mainviews.last_order),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$','django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^market/', include('client.urls', namespace='client')),
    url(r'^hq/', include('hq.urls', namespace='hq')),
    url(r'^udffeed/', include('udffeed.urls', namespace='udffeed')),
    url(r'^password_reset/$','django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm'),
]

client/models.py
from django.db import models
from django.contrib.auth.models import User
from pseparser.models import Company
from django.shortcuts import get_object_or_404

# Create your models here.
class Client(models.Model):
    user = models.OneToOneField(User)
    last_name = models.CharField(max_length=20)
    first_name = models.CharField(max_length=20)
    wallet = models.DecimalField(decimal_places=2, max_digits=20)
    watchlist = models.ManyToManyField(Company, related_name='watching', blank=True)
    agents = models.CharField(max_length=20, blank=True)
    LANGUAGE_CHOICES = (
        ('ja', 'Japanese'),
        ('en', 'English'),
    )
    language = models.CharField(
        max_length=2,
        choices=LANGUAGE_CHOICES,
        default='en',
        blank=True
    )
    def __str__(self):
        return str(self.last_name +', '+ self.first_name)

class Order(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    client = models.ForeignKey(Client)
    stock = models.ForeignKey(Company)
    METHOD_CHOICES = (
        ('B', 'Buy'),
        ('S', 'Sell'),
    )
    method = models.CharField(
        max_length=1,
        choices=METHOD_CHOICES,
        default='B',
    )
    ORDER_TYPE_CHOICES = (
        ('L', 'Limit Order'),
        ('O', 'Stop Order'),
        ('C', 'One Cancel Other Order')
    )
    order_type = models.CharField(
        max_length=1,
        choices=ORDER_TYPE_CHOICES,
        default='L',
    )
    EXECUTION_TYPE_CHOICES = (
        ('OP', 'Order Price'),
        ('MO', 'Market Order'),
        ('BP', 'Best Price'),
        ('LO', 'Limit Order'),
        ('WO', 'Width Order'),
        ('OC', 'One Cancel Other Order')
    )
    execution_type = models.CharField(
        max_length=2,
        choices=EXECUTION_TYPE_CHOICES,
        default='OP',
    )
    price = models.DecimalField(decimal_places=2, max_digits=20)
    upper_limit = models.DecimalField(decimal_places=2, max_digits=20)
    units = models.IntegerField()
    EXPIRATION_CHOICES = (
        ('C', 'Good Til Cancelled'),
        ('D', 'Good Til Date'),
    )
    expiration = models.CharField(
        max_length=1,
        choices=EXPIRATION_CHOICES,
        default='C',
    )
    STATUS_CHOICES = (
        ('Pen', 'Pending'),
        ('Par', 'Queued'),
        ('Inc', 'Partial'),
        ('Exe', 'Executed'),
        ('Rev', 'Processing'),
        ('Rej', 'Rejected'),
        ('Can', 'Cancelled'),
    )
    status = models.CharField(
        max_length=3,
        choices=STATUS_CHOICES,
        default='Pen',
    )
    charge = models.DecimalField(decimal_places=2, max_digits=20, default=0)
    others = models.CharField(max_length=30, blank=True, null=True)


class Transaction(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(decimal_places=2, max_digits=20, default=0)
    client = models.ForeignKey(Client)
    TRANSACTION_TYPE_CHOICES = (
        ('B', 'Buy'),
        ('S', 'Sell'),
        ('D', 'Dividend'),
        ('W', 'Withdrawal'),
        ('A', 'Add Fund'),
    )
    order_type = models.CharField(
        max_length=1,
        choices=TRANSACTION_TYPE_CHOICES,
        default='B',
    )
    note = models.CharField(max_length=30, blank=True, null=True)


class AdminNotification(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    client = models.ForeignKey(Client)
    order = models.IntegerField()
    message = models.CharField(max_length=30, blank=True, null=True)
    seen = models.IntegerField(default=0)

    def __str__(self):
        return str(self.message)

class Alert(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=30, blank=True, null=True)
    client = models.ForeignKey(Client)
    seen = models.IntegerField(default=0)

    def __str__(self):
        return str(self.message)

client/forms.py
from django import forms
from .models import *
from pseparser.models import *

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['method', 'client', 'stock', 'order_type', 'execution_type', 'price', 'upper_limit', 'units', 'expiration', 'others', 'charge']

class EditOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['order_type', 'execution_type', 'price', 'upper_limit', 'units', 'status', 'others', 'charge']

class AddToWatchlistForm(forms.Form):
    add = forms.IntegerField()

class ChangePasswordForm(forms.Form):
	newpassword= forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30)), label=("New Password"))
	renewpasssword=forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30)), label=("Retype New Password"))
		
class ContactForm(forms.Form):
    subject = forms.CharField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

client/templates/client/en/account.html
{% extends 'client/en/base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}

{% block content %}


<div class="row">
	<div class="large-6 large-offset-3">
		<h2><br>Hi {{ client.first_name }} {{ client.last_name }}</h2>
		<p class="show-for-small-only"><a href="http://mft-roi.com/logout">Logout</a></p>
		<h4>Change Password for {{ client.user }}</h4>
		<form action="{% url 'client:account' %}" method="POST" >{% csrf_token %}

			{{form}}
			<input type="submit" class="button" value="Save Changes" />

		</form>	
	</div>
</div>



{% endblock %}

client/templates/client/en/edit_order.html
{% extends 'client/en/base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}

{% block content %}
    

    <div class="row">
      <div class="large-4 columns">
        <div class="module">
          <div class="module-content" id="tranasction_form">
            <div class="large-12 columns">
              <form action="{% url 'client:edit_order' order.id %}" method="post"  id="stock-form">
                <h5>[{{ order.get_method_display|upper }}ING STOCK]</h5>
                {% csrf_token %}
                {{ form }}

    <!--             <label for="id_order_type">Order type:</label>
                <input name="order_type" id="id_order_type" value="{{ order.get_order_type_display }}">

                <label for="id_execution_type">Execution type:</label>
                <input name="execution_type" id="id_execution_type" value="{{ order.get_execution_type_display }}">

                <label  for="id_units">Units:</label>
                <input name="units" id="id_units" type="number" value="{{ order.units }}">

                <input id="id_price" name="price" step="0.01" type="number" value="{{ order.price }}" class="back-0" style="display:none;">
                <div class="expectedcost-text" style="padding-bottom:15px;">
                  株価: <span id="stock-cost" class="costs">0</span><br>
                  手数料など: <span id="fees" class="costs">0</span><br>
                  合計: <span id="total-cost" class="costs">0</span><br>
                </div>
     -->
                

                
    <!--             {{ order.upper_limit }}
                {{ order.get_expiration_display }}
                {{ order.price }}
                {{ order.units }}
                {{ order.get_status_display }}
     -->
                <button id="id_status" name="status" class="button expanded" value="Pen" type="submit">Revise Order</button>
                <button id="id_status" name="status" class="button expanded" value="Can" type="submit">Cancel Order</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="large-8 columns">
        <div class="row">
          <div class="large-12 columns stock-title">
            <span class="stock-symbol">{{ company.symbol }}</span> - {{ company.company_name }}
          </div>
          <div class="large-12 columns stock-details">
            <div class="row">
              <div class="large-4 columns" style="border-right:1px #ccc solid;">
                <div class="stock-highlight">{{last_price|floatformat:2}}</div>
                <div class="stock-label">Last Price</div>
              </div>
              <div class="large-4 columns" style="border-right:1px #ccc solid;">
                <div class="stock-highlight">
                  {% if indicator == 'U' %}
                  <span class="up">
                  {% elif indicator == 'D' %}
                  <span class="down">
                  {% else %}
                  <span class="same">
                  {% endif %}
                  {{change|floatformat:2}}
                  </span>
                </div>
                <div class="stock-label">Change in Points</div>
              </div>
              <div class="large-4 columns">
                <div class="stock-highlight">
                  {% if indicator == 'U' %}
                  <span class="up">
                  {% elif indicator == 'D' %}
                  <span class="down">
                  {% else %}
                  <span class="same">
                  {% endif %}
                  {{percent_change|floatformat:2}}
                  </span>
                </div>
                <div class="stock-label">Percentage Change</div>
              </div>
              <div class="large-4 columns" style="border-right:1px #ccc solid;">
                <hr>
                <div class="stock-highlight">{{low_price|floatformat:2}} - {{high_price|floatformat:2}} </div>
                <div class="stock-label">Day Range</div>
              </div>
              <div class="large-4 columns" style="border-right:1px #ccc solid;">
                <hr>
                <div class="stock-highlight">{{latest_stock.total_volume|floatformat:0}}</div>
                <div class="stock-label">Volume</div>
              </div>
              <div class="large-4 columns">
                <hr>
                <div class="stock-highlight">{{close_price|floatformat:2}}</div>
                <div class="stock-label">Previous Close</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div id="buy-information">
      <div id="stock-buy" class="module">
        <div class="wrap" id="revise">
          
          
        </div>
      </div>
    </div>

    <script>

      function formvalidate() {
        CalculateCost();
        var conceptName = $('#id_execution_type').find(":selected").val();

        action = title;
        stock = $("#stock-name h3").html();
        price = $("#order-price").val();
          limit = $("#id_upper_limit").val();
          best = $('#stockprice').val();

          if(conceptName == 'MO') {
            price = price;
          } else if (conceptName == 'BP'){
              price = best;
          } else {
            if(conceptName == 'WO') {
              price = limit;
            } else {
              price = price;
            }
          }

        cost = price;
        units = $("#id_units").val();

        if (action == "Buy"){
          actiondisplay = "buying";
        } else {
          actiondisplay = "selling";
        }

        var r = confirm("Thank you! 以下の内容で注文します。\n会社名: " +  stock + " \n株数: " +  units + "\n入札価格: " + cost);
        if (r == true) {
            $( "#stock-form" ).submit();
        } else {
          return false;
        }
      }


      $( document ).ready(function() {

          

          

          $("label[for='id_units']").html('Units');
          $('#id_status').css('display','none');
          $('label[for=id_status]').css('display','none');
          $('#id_others').css('display','none');
          $('label[for=id_others]').css('display','none');
          $('#id_price').css('display','none');
          $('label[for=id_price]').css('display','none');
          $('#id_upper_limit').css('display','none');
          $('label[for=id_upper_limit]').css('display','none');
          $('label[for=id_order_type').css('display','none');
          $('label[for=id_execution_type').css('display','none');
          $('#id_order_type').css('display','none');
          $('#id_execution_type').css('display','none');
          $('label[for=id_charge]').css('display','none');
          $('#id_charge').css('display','none');


          var ord = $('#id_order_type').find(":selected").val();

          $("#id_price").after("<label for=\"order-price\">Order Price</label><input id=\"order-price\" type=\"number\" step=\"0.0001\" value=\"0\">");
          $("#id_execution_type").after("<label for=\"stockprice\" id=\"stockpricelabel\" style=\"display:none;\">もし株価が〜ペソになったら</label><input id=\"stockprice\" type=\"number\" value=\"0\" step=\"any\" style=\"display:none;\">");

          title = $('#order_method').html();



          var exec = $('#id_execution_type').find(":selected").val();

          $('#upper_limit').css('display','none');
          $('label[for=upper_limit]').css('display','none');
          $('#order-price').css('display','none');
          $('label[for=order-price]').css('display','none');

          totalcost = $("#id_price").val();
          units = $("#id_units").val();

          $("#order-price").val(parseInt(totalcost)/parseInt(units).toFixed(2));

          price = parseFloat($('#order-price').val()).toFixed(2);
          $('#order-price').val(price);

          $('#stockprice').val(price);


          switch(exec){
            case 'OP':
              $('#order-price').css('display', 'block');
              $('label[for="order-price"]').css('display', 'block');
              break;
            case 'MO':
              $('.mo').css('display', 'block');
              break;
            case 'BP':
              $('label[for="stockprice"]').css('display', 'block');
              $('#stockprice').css('display', 'block');
              break;
            case 'LO':
              $('#order-price').css('display', 'block');
              $('label[for="order-price"]').css('display', 'block');
              $('label[for="stockprice"]').css('display', 'block');
              $('#stockprice').css('display', 'block');
              break;
            case 'WO':
              $('#id_upper_limit').css('display','block');
              $('label[for="id_upper_limit"]').css('display','block');
              $('label[for="stockprice"]').css('display', 'block');
              $('#stockprice').css('display', 'block');
              break;
          }
      });

      function CalculateCost() {
          var conceptName = $('#id_execution_type').find(":selected").val();

          units = $("#id_units").val();
          price = $("#order-price").val();
          limit = $("#id_upper_limit").val();
          best = $('#stockprice').val();

          if(conceptName == 'MO') {
            price = price;
          } else if (conceptName == 'BP'){
              price = best;
          } else {
            if(conceptName == 'WO') {
              price = limit;
            } else {
              price = price;
            }
          }


          lastprice2 = parseFloat(price);
          lastprice3 = (lastprice2*units);
          commision = lastprice3*0.01;
          title = $('#action').html();
          

          if(title == 'Sell') {
              if (commision <= 150) {
                  sellcommision = lastprice3 * 0.005;
                  lastpricewithcommision = lastprice3 - (168 + lastprice3*0.00015 + sellcommision);
              } else {
                  lastpricewithcommision = lastprice3*0.98365;
              }
          } else {
              if (commision <= 150) {
                  lastpricewithcommision = lastprice3 + 168 + lastprice3*0.00015;
              } else {
                  lastpricewithcommision = lastprice3*1.01135;
              }
          }

          $('#id_price').val(lastprice3.toFixed(2));

          lot = $("#lot-size-text").text();
          lot = parseFloat(lot);

          if(units % lot === 0 && units > 0){
            $('#stock-form .revise').removeAttr('disabled');
          } else {
            $('#stock-form .revise').attr('disabled','disabled');
          }


        }

      $("#id_units").keyup(function() {
        CalculateCost();
      });

      $("#order-price").keyup(function() {
        CalculateCost();
      });

          
    </script>

   <!--  <script>
      function CalculateCost() {
        var conceptName = $('#id_execution_type').val();

        units = $("#id_units").val();
        lastprice = $("#last-price-text").html();
        orderprice = $("#order-price").val();
        stockgoes = $("#stockprice").val();

        if(conceptName == 'MO') {
          stockprice = lastprice;
        } else if (conceptName == 'BP'){
            stockprice = stockgoes;
        } else {
            stockprice = orderprice;
        }

        lastprice2 = parseFloat(stockprice);
        lastprice3 = (lastprice2*units);
        commision = lastprice3*0.01;
        title = $('#action').html();
        

        if(title == 'Sell') {
            if (commision <= 150) {
                sellcommision = lastprice3 * 0.005;
                lastpricewithcommision = lastprice3 - (168 + lastprice3*0.00015 + sellcommision);
            } else {
                lastpricewithcommision = lastprice3*0.98365;
            }
        } else {
            if (commision <= 150) {
                lastpricewithcommision = lastprice3 + 168 + lastprice3*0.00015;
            } else {
                lastpricewithcommision = lastprice3*1.01135;
            }
        }

        $('#id_price').val(lastpricewithcommision.toFixed(2));
        $('#fees').html((lastpricewithcommision-lastprice3).toFixed(2));
        $('#stock-cost').html(lastprice3.toFixed(2));
        $('#total-cost').html(lastpricewithcommision.toFixed(2));

        lot = $("#lot-size-text").text();

        if(units % lot === 0 && units > 0){
          $('#stock-form .button').removeAttr('disabled');
        } else {
          $('#stock-form .button').attr('disabled','disabled');
        }

      }

      $("#id_units").keyup(function() {
        CalculateCost();
      });

      $("#order-price").keyup(function() {
        CalculateCost();
      });

    </script> -->




{% endblock %}

client/templates/client/en/login.html
{% block content %}

{% if form.errors %}
<p>! Sorry your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'client:login' %}">
{% csrf_token %}
<div>


LogIn !!
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

</div>
{% endblock %}

client/templates/client/en/orders.html
{% extends 'client/en/base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}

{% block head %}
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<script src="http://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('#ordersTable').DataTable({
        "order": [[ 0, "desc" ]],
        "pageLength": 20
    });
});
</script>
{% endblock %}

{% block content %}
    {% include 'user-info.html' %}

    <div id="transaction-and-ads">
      <div id="transactions" class="module">

      	<table id="ordersTable">
		    <thead>
		        <tr>
		            <th>注文日時</th>
		            <th>取引状態</th>
		            <th>会社名</th>
		            <th>株式数</th>
		            <th>Method</th>
		            <th>株式購入額</th>
		        </tr>
		    </thead>
		    <tbody>
		        {% for order in order_set.all %}
		        <tr class="{{ order.order_type }}">
		        	<td>{{order.date_created}}</td>
		            <td>{{order.get_status_display}}</td>
		            <td>
		            	<span class="action">
			              {% if order.status = 'Pen'  %}
			              <a href="{% url 'client:edit_order' order.id %}" class="btn btn-primary btn-sm" style="background-color: #aaa; padding: 5px; color: #fff; border-radius: 3px;">Revise</a>
			              {% else %}
			              <a href="#" class="btn btn-primary btn-sm" style="background-color: #fff; padding: 5px; color: #aaa; border-radius: 3px;">Locked</a>
			              {% endif %}
			            </span>
			            &nbsp;&nbsp;&nbsp;<span class="stock-name-1">{{order.stock}}</span>
		            </td>
		            <td>{{order.units}}</td>
		            <td>
		            	{% if order.method = 'B' %}
			              株式購入<!--Buy-->
			            {% else %}
			              株式売却<!--Sell-->
			            {% endif %}
		            </td>
		            <td>{{order.price|intcomma}}</td>
		        </tr>
		        {% endfor %}
		    </tbody>
		</table>

      </div>
    </div>

{% endblock %}

client/templates/client/en/portfolio.html
{% extends 'client/en/base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}


{% block content %}

    <script>

      $( function() {
        $( "#trade_link" ).addClass( "selected" );
      });
    </script>


    <div class="row">
      <div class="large-12 columns">
        <div class="module">
          <div class="module-header">
            <div class="large-12 columns module-title">
              Portfolio
            </div>
          </div>
          <div class="module-content" id="portfolio">
            <div class="large-12 columns">
              <table>
                <tr class="table-header"> 
                  <td>Stock</td>
                  <td>Holding</td>
                  <td>Ave. Price</td>
                  <td>Total Cost</td>
                  <td>Total Value</td>
                  <td>Total Change</td>
                  <td>Sell</td>
                </tr>
                {% for key, value in portfolio.items %}
                <tr class="portfolio-position">
                  <td>
                    <div class="stock-line-1">
                      <a href="{% url 'client:stock' key.symbol %}" style="color:#666;">{{ key.symbol }}</a> <span class="price">{{ value.stockprice.last_traded_price|floatformat:2|intcomma }}</span> 
                      {% if value.stockprice.indicator == 'U' %}
                      <span class="up">
                      {% elif value.stockprice.indicator == 'D' %}
                      <span class="down">
                      {% else %}
                      <span class="same">
                      {% endif %}
                      ({{ value.stockprice.percentage_change_close|floatformat:2 }})
                      </span>
                    </div>
                    <div class="stock-line-2">
                      <a href="{% url 'client:stock' key.symbol %}" style="color:#666;">{{ key }}</a>
                    </div>
                  </td>
                  <td class="table-details">{{ value.units|intcomma }}</td>
                  <td class="table-details">
                    {% if value.price|div:value.units >= 1 %}
                    {{ value.price|div:value.units|floatformat:2 }}
                    {% else %}
                    {{ value.price|div:value.units|floatformat:4 }}
                    {% endif %}
                  </td>
                  <td class="table-details">
                    {{ value.price|add:value.charge|floatformat:2|intcomma|intcomma }}
                  </td>
                  <td class="table-highlight">
                  {% if value.stockprice.last_traded_price|mul:value.units|sub:value.price > 0 %}
                  <span class="up">
                  {% elif value.stockprice.last_traded_price|mul:value.units|sub:value.price < 0 %}
                  <span class="down">
                  {% else %}
                  <span class="same">
                  {% endif %}
                  {{ value.stockprice.last_traded_price|mul:value.units|floatformat:2|intcomma }}
                  </span>
                  </td>
                  <td class="table-highlight">
                  {% if value.stockprice.last_traded_price|mul:value.units|sub:value.price > 0 %}
                  <span class="up">
                  {% elif value.stockprice.last_traded_price|mul:value.units|sub:value.price < 0 %}
                  <span class="down">
                  {% else %}
                  <span class="same">
                  {% endif %}
                  {{ value.stockprice.last_traded_price|mul:value.units|sub:value.price|floatformat:2|intcomma }} ({{ value.stockprice.last_traded_price|mul:value.units|sub:value.price|div:value.price|mul:100|floatformat:2 }})
                  </span></td>
                  <td><a href="{% url 'client:sell' key.symbol %}" class="sell">Sell</a>&nbsp;<a href="{% url 'client:buy' key.symbol %}" class="sell" style="background-color:#258dad">Buy</a></td>
                </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="large-8 columns">
        <div class="module">
          <div class="module-header">
            <div class="large-12 columns module-title">
              Orders
            </div>
          </div>
          <div class="module-content" id="portfolio">
            <div class="large-12 columns">
              <table>
                <tr class="table-header"> 
                  <td>Type</td>
                  <td>Stock</td>
                  <td>Units</td>
                  <td>Price</td>
                  <td>Total Cost</td>
                  <td>Status</td>
                  <td>&nbsp;</td>
                </tr>
                {% for order in order_set.all %}
                <tr>
                  <td class="table-highlight">
                    {% if order.method == 'S' %}
                    <span class="sell-text">
                    {% else %}
                    <span class="buy-text">
                    {% endif %}
                      {{order.get_method_display}}
                    </span>
                  </td>
                  <td class="table-highlight">{{order.stock.symbol}}</td>
                  <td class="table-details">{{order.units|intcomma}}</td>
                  <td class="table-details">{{order.price|div:order.units|intcomma}}</td>
                  <td class="table-details">{{order.price|add:order.charge|intcomma}}</td>
                  <td class="table-details">
                    {% if order.status = 'Rev' %}
                      Queued
                    {% else %}
                      {{order.get_status_display}}
                    {% endif %}
                  </td>
                  <td>
                    {% if order.status = 'Exe' or order.status = 'Can' or order.status = 'Inc' %}
                      &nbsp;
                    {% elif order.status = 'Rev' %}
                      <span data-tooltip aria-haspopup="true" class="has-tip" data-disable-hover="false" tabindex="1" title="Your order was locked because of one of the following reasons: 1) the order price has been triggered or very near the current price 2) Market status is pre-open or pre-close">Locked</span>
                    {% else %}
                      <a href="{% url 'client:edit_order' order.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="large-4 columns">
        <div class="module">
          <div class="module-header">
            <div class="large-12 columns module-title">
              Wallet History
            </div>
          </div>
          <div class="module-content">
            <div class="large-12 columns">
              <table>
                <tr class="table-header"> 
                  <td>Transaction</td>
                  <td>Amount</td>
                </tr>
                {% for transaction in wallet_set.all %}
                <tr class="portfolio-position">
                  <td class="table-highlight">{{transaction.note}}</td>
                  <td class="table-details">{{transaction.amount|intcomma}}</td>
                </tr>
                {% endfor %}
               
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>



{% endblock %}

client/templates/client/en/user-info.html
{% load humanize %}
{% load mathfilters %}

  